language: java
jdk:
  - oraclejdk8

sudo: required
services:
  - docker

install: true

before_script:
  - export TZ='Asia/Shanghai' && date
  - docker login -u $AZURE_CR_USERNAME -p $AZURE_CR_PASSWORD $AZURE_CR_LOGIN_SERVER
  - perl -pi -e 's/\$\{your-docker-image-prefix\}/$ENV{AZURE_CR_LOGIN_SERVER}/g' initializr-service/pom.xml
  - perl -pi -e 's/\$\{your-docker-image-name\}/azure-spring-cloud/g' initializr-service/pom.xml
#    if: branch = master

jobs:
  include:
    - stage: build
      script: ./mvnw clean package -DskipTests -Pfull
    - stage: docker push
      script: ./mvnw clean install -DskipTests -Pfull && docker images
      if: branch = make-master-branch-to-push-images AND type != pull_request

