= Azure Spring Cloud Playground

Azure Spring Cloud Playground helps you scaffold and generate Microservice projects.
It provides you with native Spring Cloud modules as well as modules developed for
connecting to and consuming Azure related services. The generated Microservice projects
follow https://12factor.net/[The Twelve-Factor App] methodology and are ready to run
 with docker compose on local development host or deploy to Kubernetes or Cloud Foundy in the Cloud.

== Getting Started
* Install https://maven.apache.org/install.html[Maven] and https://docs.docker.com/install/[Docker]
* Access to https://azure-spring-cloud.azurewebsites.net/[azure-spring-cloud.azurewebsites.net]
* Sign in with your Azure subscription. If you don't have a Azure subscription get a https://azure.microsoft.com/en-us/free/[free one].
* Select the modules you'd like to start with and generate the project.
* Extract and go to project root directory, run the following:
```
cd docker
run.cmd (run.sh)
```
* After all microservices start, access gateway endpoint at http://localhost:9999

== Deploy to Azure
link:DEPLOY_TO_AZURE.adoc[Deploy Spring Cloud Playground to Azure]

== Architecture
TBD

== Supported Modules
The following modules are supported:

* `Spring Cloud Config Server`: Central management for configuration via a git or svn backend
* `Spring Cloud Gateway`: Intelligent and programmable routing with the reactive Spring Cloud Gateway
* `Spring Cloud Eureka Server`: Spring Cloud Service Registry and Discovery
* `Spring Cloud Hystrix Dashboard`: Circuit breaker dashboard with spring-cloud-netflix Hystrix

== CI/CD
TBD

== Reference
https://github.com/spring-io/initializr[Spring Initializr]

== License
Azure Spring Cloud Playground is released under the
http://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license].

== Contributing

This project welcomes contributions and suggestions.  Most contributions require you to agree to a Contributor License Agreement (CLA) declaring that you have the right to, and actually do, grant us the rights to use your contribution. For details, visit https://cla.microsoft.com.

This project has adopted the https://opensource.microsoft.com/codeofconduct/[Microsoft Open Source Code of Conduct].
For more information see the https://opensource.microsoft.com/codeofconduct/faq/[Code of Conduct FAQ] or
contact [opencode@microsoft.com](mailto:opencode@microsoft.com) with any additional questions or comments.