server:
  port: 9999

spring:
  cloud:
    gateway:
      routes:
      {{#services}}
      - id: {{applicationName}}
        uri: lb://{{applicationName}}
        predicates:
        - Path=/{{applicationName}}/**
      {{/services}}